"""financial module: accounts payable/receivable

Revision ID: 54ca32bcb947
Revises: f6c73f20f0c9
Create Date: 2026-07-07 16:56:38.518533
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '54ca32bcb947'
down_revision: str | None = 'f6c73f20f0c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum type names introduced by this migration (dropped on downgrade for PG).
_NEW_ENUMS = (
    "financial_direction_enum",
    "financial_status_enum",
    "financial_category_kind_enum",
    "bank_transaction_type_enum",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 'status_enum' already exists (initial migration). On PostgreSQL reference
    # it without re-creating the type; the enums above are new.
    is_pg = op.get_bind().dialect.name == "postgresql"
    status_enum = (
        postgresql.ENUM("ativo", "inativo", name="status_enum", create_type=False)
        if is_pg
        else sa.Enum("ativo", "inativo", name="status_enum")
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('agency', sa.String(length=20), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_name'), 'bank_accounts', ['name'], unique=False)
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_name'), 'cost_centers', ['name'], unique=False)
    op.create_table('financial_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('receita', 'despesa', name='financial_category_kind_enum'), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_categories_name'), 'financial_categories', ['name'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_name'), 'payment_methods', ['name'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('receber', 'pagar', name='financial_direction_enum'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('document', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('em_aberto', 'parcial', 'quitado', 'vencido', 'cancelado', 'renegociado', name='financial_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['financial_categories.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_customer_id'), 'financial_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_direction'), 'financial_accounts', ['direction'], unique=False)
    op.create_index(op.f('ix_financial_accounts_document'), 'financial_accounts', ['document'], unique=False)
    op.create_index(op.f('ix_financial_accounts_status'), 'financial_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_financial_accounts_supplier_id'), 'financial_accounts', ['supplier_id'], unique=False)
    op.create_table('financial_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('fine', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('addition', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('em_aberto', 'parcial', 'quitado', 'vencido', 'cancelado', 'renegociado', name='financial_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_installments_account_id'), 'financial_installments', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_installments_due_date'), 'financial_installments', ['due_date'], unique=False)
    op.create_index(op.f('ix_financial_installments_status'), 'financial_installments', ['status'], unique=False)
    op.create_table('financial_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('fine', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['installment_id'], ['financial_installments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_settlements_installment_id'), 'financial_settlements', ['installment_id'], unique=False)
    op.create_index(op.f('ix_financial_settlements_is_cancelled'), 'financial_settlements', ['is_cancelled'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('credito', 'debito', name='bank_transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['financial_settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_financial_settlements_is_cancelled'), table_name='financial_settlements')
    op.drop_index(op.f('ix_financial_settlements_installment_id'), table_name='financial_settlements')
    op.drop_table('financial_settlements')
    op.drop_index(op.f('ix_financial_installments_status'), table_name='financial_installments')
    op.drop_index(op.f('ix_financial_installments_due_date'), table_name='financial_installments')
    op.drop_index(op.f('ix_financial_installments_account_id'), table_name='financial_installments')
    op.drop_table('financial_installments')
    op.drop_index(op.f('ix_financial_accounts_supplier_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_status'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_document'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_direction'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_customer_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_payment_methods_name'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_financial_categories_name'), table_name='financial_categories')
    op.drop_table('financial_categories')
    op.drop_index(op.f('ix_cost_centers_name'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_bank_accounts_name'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # Drop only the enum types introduced here; 'status_enum' is shared and kept.
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in _NEW_ENUMS:
            sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
