"""sale price, order extra cost and item cost snapshot

Revision ID: f6c73f20f0c9
Revises: ff333c9fc5d9
Create Date: 2026-07-06 10:27:18.712633
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f6c73f20f0c9'
down_revision: str | None = 'ff333c9fc5d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('extra_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_price')
    op.drop_column('orders', 'extra_cost')
    op.drop_column('order_items', 'unit_cost')
    # ### end Alembic commands ###
